#python ./scripts/run_benchmark.py --config-path "rolling_forecast_config.json" --data-name-list "ETTh2.csv" --strategy-args '{"horizon": 96}' --model-name "time_series_library.PatchTST" --model-hyper-params '{"d_ff": 128, "d_model": 32, "horizon": 96, "norm": true, "seq_len": 512}' --adapter "transformer_adapter" --gpus 0 --num-workers 1 --timeout 60000 --save-path "ETTh2/PatchTST"
#
#python ./scripts/run_benchmark.py --config-path "rolling_forecast_config.json" --data-name-list "ETTh2.csv" --strategy-args '{"horizon": 192}' --model-name "time_series_library.PatchTST" --model-hyper-params '{"d_ff": 128, "d_model": 32, "horizon": 192, "norm": true, "seq_len": 512}' --adapter "transformer_adapter" --gpus 0 --num-workers 1 --timeout 60000 --save-path "ETTh2/PatchTST"
#
#python ./scripts/run_benchmark.py --config-path "rolling_forecast_config.json" --data-name-list "ETTh2.csv" --strategy-args '{"horizon": 336}' --model-name "time_series_library.PatchTST" --model-hyper-params '{"d_ff": 128, "d_model": 32, "horizon": 336, "norm": true, "seq_len": 512}' --adapter "transformer_adapter" --gpus 0 --num-workers 1 --timeout 60000 --save-path "ETTh2/PatchTST"
#
#python ./scripts/run_benchmark.py --config-path "rolling_forecast_config.json" --data-name-list "ETTh2.csv" --strategy-args '{"horizon": 720}' --model-name "time_series_library.PatchTST" --model-hyper-params '{"d_ff": 128, "d_model": 32, "horizon": 720, "norm": true, "seq_len": 336}' --adapter "transformer_adapter" --gpus 0 --num-workers 1 --timeout 60000 --save-path "ETTh2/PatchTST"
#


python ./scripts/run_benchmark.py --config-path "rolling_forecast_config.json" --data-name-list "ETTh2.csv" --strategy-args '{"horizon": 96}' --model-name "time_series_library.PatchTST" --model-hyper-params '{"batch_size": 32, "d_model": 512, "dff": 2048, "dropout": 0.25, "head_dropout": 0.1, "horizon": 96, "lr": 0.0001, "lradj": "type1", "n_heads": 1, "norm": true, "patch_len": 24, "patience": 5, "seq_len": 512, "stride": 24}'  --gpus 5 --adapter "transformer_adapter" --num-workers 1 --timeout 60000 --save-path "ETTh2/PatchTST"

python ./scripts/run_benchmark.py --config-path "rolling_forecast_config.json" --data-name-list "ETTh2.csv" --strategy-args '{"horizon": 192}' --model-name "time_series_library.PatchTST" --model-hyper-params '{"batch_size": 32, "d_model": 128, "dff": 256, "dropout": 0.2, "head_dropout": 0, "horizon": 192, "lr": 0.0001, "lradj": "type1", "n_heads": 1, "norm": true, "patch_len": 24, "patience": 5, "seq_len": 336, "stride": 24}'  --gpus 5 --adapter "transformer_adapter" --num-workers 1 --timeout 60000 --save-path "ETTh2/PatchTST"

python ./scripts/run_benchmark.py --config-path "rolling_forecast_config.json" --data-name-list "ETTh2.csv" --strategy-args '{"horizon": 336}' --model-name "time_series_library.PatchTST" --model-hyper-params '{"batch_size": 128, "d_model": 512, "dff": 1024, "dropout": 0.4, "head_dropout": 0, "horizon": 336, "lr": 0.0001, "lradj": "type1", "n_heads": 1, "norm": true, "patch_len": 24, "patience": 5, "seq_len": 336, "stride": 24}'  --gpus 5 --adapter "transformer_adapter" --num-workers 1 --timeout 60000 --save-path "ETTh2/PatchTST"

python ./scripts/run_benchmark.py --config-path "rolling_forecast_config.json" --data-name-list "ETTh2.csv" --strategy-args '{"horizon": 720}' --model-name "time_series_library.PatchTST" --model-hyper-params '{"batch_size": 128, "d_model": 512, "dff": 1024, "dropout": 0.4, "head_dropout": 0.1, "horizon": 720, "lr": 0.0001, "lradj": "type1", "n_heads": 1, "norm": true, "patch_len": 24, "patience": 5, "seq_len": 336, "stride": 24}'  --gpus 5 --adapter "transformer_adapter" --num-workers 1 --timeout 60000 --save-path "ETTh2/PatchTST"

