#python ./scripts/run_benchmark.py --config-path "rolling_forecast_config.json" --data-name-list "Electricity.csv" --strategy-args '{"horizon": 96}' --model-name "time_series_library.PatchTST" --model-hyper-params '{"batch_size": 64, "d_ff": 512, "d_model": 128, "horizon": 96, "lr": 0.0001, "norm": true, "seq_len": 512}' --adapter "transformer_adapter" --gpus 0 --num-workers 1 --timeout 60000 --save-path "Electricity/PatchTST"
#
#python ./scripts/run_benchmark.py --config-path "rolling_forecast_config.json" --data-name-list "Electricity.csv" --strategy-args '{"horizon": 192}' --model-name "time_series_library.PatchTST" --model-hyper-params '{"batch_size": 64, "d_ff": 512, "d_model": 128, "horizon": 192, "lr": 0.0001, "norm": true, "seq_len": 512}' --adapter "transformer_adapter" --gpus 0 --num-workers 1 --timeout 60000 --save-path "Electricity/PatchTST"
#
#python ./scripts/run_benchmark.py --config-path "rolling_forecast_config.json" --data-name-list "Electricity.csv" --strategy-args '{"horizon": 336}' --model-name "time_series_library.PatchTST" --model-hyper-params '{"batch_size": 16, "d_ff": 1024, "d_model": 512, "horizon": 336, "lr": 0.0005, "norm": true, "num_epochs": 20, "seq_len": 512}' --adapter "transformer_adapter" --gpus 0 --num-workers 1 --timeout 60000 --save-path "Electricity/PatchTST"
#
#python ./scripts/run_benchmark.py --config-path "rolling_forecast_config.json" --data-name-list "Electricity.csv" --strategy-args '{"horizon": 720}' --model-name "time_series_library.PatchTST" --model-hyper-params '{"batch_size": 64, "d_ff": 512, "d_model": 128, "horizon": 720, "lr": 0.0001, "norm": true, "seq_len": 512}' --adapter "transformer_adapter" --gpus 0 --num-workers 1 --timeout 60000 --save-path "Electricity/PatchTST"
#


python ./scripts/run_benchmark.py --config-path "rolling_forecast_config.json" --data-name-list "Electricity.csv" --strategy-args '{"horizon": 96}' --model-name "time_series_library.PatchTST" --model-hyper-params '{"batch_size": 64, "d_model": 512, "dff": 1024, "dropout": 0.1, "e_layers": 2, "head_dropout": 0.1, "hidden_size": 128, "horizon": 96, "lr": 0.0005, "lradj": "type3", "num_epochs": 100, "loss": "MAE", "patience":5, "n_heads": 4, "norm": true, "patch_len": 24, "seq_len": 512, "stride": 24}'  --gpus 0 --adapter "transformer_adapter" --num-workers 1 --timeout 60000 --save-path "Electricity/PatchTST"

python ./scripts/run_benchmark.py --config-path "rolling_forecast_config.json" --data-name-list "Electricity.csv" --strategy-args '{"horizon": 192}' --model-name "time_series_library.PatchTST" --model-hyper-params '{"batch_size": 64, "d_model": 512, "dff": 1024, "dropout": 0.1, "e_layers": 2, "head_dropout": 0.1, "hidden_size": 128, "horizon": 192, "lr": 0.0004, "lradj": "type3", "num_epochs": 100, "loss": "MAE", "patience":5, "n_heads": 4, "norm": true, "patch_len": 24, "seq_len": 512, "stride": 24}'  --gpus 0 --adapter "transformer_adapter" --num-workers 1 --timeout 60000 --save-path "Electricity/PatchTST"

python ./scripts/run_benchmark.py --config-path "rolling_forecast_config.json" --data-name-list "Electricity.csv" --strategy-args '{"horizon": 336}' --model-name "time_series_library.PatchTST" --model-hyper-params '{"batch_size": 64, "d_model": 512, "dff": 1024, "dropout": 0.1, "e_layers": 2, "head_dropout": 0.1, "hidden_size": 128, "horizon": 336, "lr": 0.0003, "lradj": "type3", "num_epochs": 100, "loss": "MAE", "patience":5, "n_heads": 4, "norm": true, "patch_len": 24, "seq_len": 512, "stride": 24}'  --gpus 0 --adapter "transformer_adapter" --num-workers 1 --timeout 60000 --save-path "Electricity/PatchTST"

python ./scripts/run_benchmark.py --config-path "rolling_forecast_config.json" --data-name-list "Electricity.csv" --strategy-args '{"horizon": 720}' --model-name "time_series_library.PatchTST" --model-hyper-params '{"batch_size": 64, "d_model": 512, "dff": 1024, "dropout": 0.1, "e_layers": 2, "head_dropout": 0.1, "hidden_size": 128, "horizon": 720, "lr": 0.0005, "lradj": "type3", "num_epochs": 100, "loss": "MAE", "patience":5, "n_heads": 4, "norm": true, "patch_len": 24, "seq_len": 512, "stride": 24}'  --gpus 0 --adapter "transformer_adapter" --num-workers 1 --timeout 60000 --save-path "Electricity/PatchTST"

